#!/bin/bash
set -Eueo pipefail
#
# This is the osc-hosts rrconf module responsible for management
# of etc/hosts file on a target machine.
#
source "${RRCONFINC}"

test "${RRUID}" -eq 0 || {
        echo "No root account."
        exit 1 
}

hostname=$(hostname)
current_date=$(date +%Y-%m-%d)

if [[ $hostname == *"zero"* ]]; then
    cp -p /home/tpribula/test "/home/tpribula/test.$current_date"
    cat osc-hosts > /home/tpribula/test
else
    echo "This osc-hosts rrconf module is responsible for management of etc/hosts file only on zero servers"
    exit 1
fi
